### ISSUE TITLE
perl Makefile.PL fails with 'String found where operator expected at Makefile.PL line 58'

### ISSUE THREAD

**Issue by merkys** [dbsrgits/sql-translator#100]
I have downloaded ZIP of the release v0.11024 from GitHub, unpacked and executed the following command:
```
perl Makefile.PL PREFIX=/usr/local/install/sql-translator/sql-translator-0.11024
```
Execution resulted in the following output:
```
include /home/andrius/src/sql-translator-0.11024/inc/Module/Install.pm
String found where operator expected at Makefile.PL line 58, near "readme_from 'lib/SQL/Translator.pm'"
	(Do you need to predeclare readme_from?)
syntax error at Makefile.PL line 58, near "readme_from 'lib/SQL/Translator.pm'"
BEGIN not safe after errors--compilation aborted at Makefile.PL line 61.
```
After commenting out the line 58 in Makefile.PL (non-crucial, I suppose), I was able to proceed with the installation.

**Comment by borisdaeppen** [comment]
I have found the same error message with `perl Makefile.PL` in current master commit 1f742579d2d66e83f3f36c22e60acb5f4930e025

**Comment by ilmari** [comment]
The tarball from GithHub is equivalent to a git checkout, and thus requires author dependencies to be installed, specifically `Module::Install::ReadmeFromPod` and `Module::Install::AuthorTests`.

I've made it explicitly list missing plugins in commit b43ba76c85f8f7726fa797810b35057023f1b423.

**Comment by merkys** [comment]
Thanks, @ilmari!
