### ISSUE TITLE
Domains are not created

### ISSUE THREAD

**Issue by KES777** [dbsrgits/sql-translator#109]
My PostgreSQL database has domains:

    CREATE DOMAIN tkol AS NUMERIC(10,3)

The domains are not created when I run:

    $(which dbic-migration) --force --schema_class App::Schema --database PostgreSQL -Ilib prepare

Currently I manually copy 001-a_domains.sql  between deployment migrations after each `prepare`

**Comment by rabbiveesh** [comment]
Hi, are you sure this is an issue in SQLT? Could you share the perl code that you used to create the domain?

It's important to see the code, b/c DBICM has a few layers of indirection, so we'd have to trace down fully where this may or may not be an issue.

**Comment by KES777** [comment]
Sorry, from today point of view I do not remember. Probably `SQL::Translator::Producer::PostgreSQL` should have something: `sub create_domain` and/or `CREATE DOMAIN ...`

**Comment by rabbiveesh** [comment]
okay, so closed in favor of #136
