### ISSUE TITLE
Homebrew sql-translator 1.59_01 upgrade failed

### ISSUE THREAD

**Issue by chenrui333** [dbsrgits/sql-translator#118]
relates to https://github.com/Homebrew/homebrew-core/pull/40047

I saw there is some build config change with this commit, https://github.com/dbsrgits/sql-translator/commit/32be8496496b7d90de447948e5e52cc7ce881cf1#diff-5d3ba18294715d9415e9e732852bfec6.

I am not quite familiar with perl build system, so I might need some help on upgrading the brew formula. :)

**Comment by ilmari** [comment]
Before running `Makefile.PL`, you need to install the modules indicated in the `.prereqs.configure.requires` key in `META.json`, i.e.:

```
$ jq .prereqs.configure.requires META.json 
{
  "ExtUtils::MakeMaker": "6.54",
  "File::ShareDir::Install": "0"
}
```

**Comment by chenrui333** [comment]
ok, cool!
