### ISSUE TITLE
Release 1.64 collateral damage

### ISSUE THREAD

**Issue by andk** [dbsrgits/sql-translator#169]
Hi veesh, I have two XRefs to fail reports that have a connection to the release 1.64:

- http://rt.perl.org/rt3/Ticket/Display.html?id=150861 : MELO/DBICx-Indexing-0.002.tar.gz
- http://rt.perl.org/rt3/Ticket/Display.html?id=150866 : CREIN/Monorail-0.4.tar.gz

It would probably be helpful to the downstream users if you could chime in in those issues and explain what they have to fix.

Thanks!

**Comment by rabbiveesh** [comment]
Thanks so much, I'll look into these ASAP.

Those links are broken for me tho, could you either double check them or
paste the bug reports here?

**Comment by andk** [comment]
Ooops, sorry:

The first link should have been https://rt.cpan.org/Ticket/Display.html?id=150861 and it currently has the following text:

Following two link lead to two test reports with the very same perl on the same machine. Betreen the two reports I upgraded SQL-Translator from 1.63 to 1.64:

- pass before: http://www.cpantesters.org/cpan/report/c38bcea2-9d07-11ee-8148-b01fdf881fbf
- fail after the upgrade: http://www.cpantesters.org/cpan/report/b312e1ca-a2f5-11ee-b568-2820f3fca046


And then second link should be https://rt.cpan.org/Ticket/Display.html?id=150866 and it currently has the text:

The following two links lead to two test reports with the very same perl on the same machine. Betreen the two reports I upgraded SQL-Translator from 1.63 to 1.64:

- pass before:  http://www.cpantesters.org/cpan/report/a1045c66-9e31-11ee-acc6-8ec64927feb5
- fail after the upgrade: http://www.cpantesters.org/cpan/report/c2a464b2-a3a7-11ee-bb84-291492aeab13


Sorry for the misconstruction of the links.

**Comment by andk** [comment]
Here is another one: https://github.com/karupanerura/SQL-Translator-Producer-DBIxSchemaDSL/issues/1 which has KARUPA/SQL-Translator-Producer-DBIxSchemaDSL-0.04.tar.gz in the focus

**Comment by rabbiveesh** [comment]
Thanks so much for the reports! I followed up on each of them.

I'm gonna leave this open for a week, and then we'll close it in the absence of more bug reports.

One of them was a subtlety about overloading, which i suppose we could improve on our side, though i could not get their tests to pass, so i have not made changes on our side anyways

**Comment by nrdvana** [comment]
The one with DBICx::Indexing is just trying to compare the field with another string.  The field object has overloaded '""', but not an overload for 'cmp' which is apparently not autogenerated from '""'.  I think adding ``` 'cmp' => sub { "$_[0]" cmp "$_[1]" } ``` might fix it.

**Comment by rabbiveesh** [comment]
thanks! I had tried playing around with overload and it wasn't behaving nicely, i'll try out your patch and see

**Comment by nrdvana** [comment]
With slightly more style:
```
cmp => sub { ("$_[0]" cmp "$_[1]")*(1-$_[2]*2) };
```

**Comment by rabbiveesh** [comment]
Looking again, DBICx::Indexing is using `cmp_deeply`, which doesn't seem to respect overloading, so they'll just have to update their test
