### ISSUE TITLE
SQL-Translator-1.65 not correctly indexed

### ISSUE THREAD

**Issue by eserte** [dbsrgits/sql-translator#174]
CPAN.pm does not know about the current version 1.65:
```
cpan[1]> m SQL::Translator                                                      
Reading '/home/e/eserte/.cpan/Metadata'
  Database was generated on Sun, 29 Sep 2024 14:17:01 GMT
Module id = SQL::Translator
    CPAN_USERID  VEESH (Avishai Goldman <CENSORED>)
    CPAN_VERSION 1.64
    CPAN_FILE    V/VE/VEESH/SQL-Translator-1.64.tar.gz
    INST_FILE    (not installed)
```
Maybe reindexing the distribution helps?

**Comment by rabbiveesh** [comment]
happy to do so; how do i accomplish that (excuse my ignorance)

**Comment by eserte** [comment]
Try (while being authenticated) https://pause.perl.org/pause/authenquery?ACTION=reindex
This will show a list of your modules and you can select which of them to reindex.

**Comment by rabbiveesh** [comment]
thanks a bunch, i have reindexed it
