### ISSUE TITLE
::Diff tries to modify old table after table rename for PK col name change

### ISSUE THREAD

**Issue by SysPete** [dbsrgits/sql-translator#40]
I tend to use PK cols which are named after the table e.g. table 'foos' has PK 'foos_id'. When renaming tables via ::Diff `->extra( renamed_from => 'foos'` then I get one of two possible breakages:

* if renamed_from is used on the column as well then I get:
```
Can't alter field in another table at .../SQL/Translator/Producer/PostgreSQL.pm line 769.
```
* if I skip the renamed_from on the PK (not a good idea in reality but an interesting test) then ::Diff gives a table rename followed by a DROP COLUMN on the table that no longer exists.

**Comment by ilmari** [comment]
This was fixed by #44, closing.
