### ISSUE TITLE
add_trigger inconsistencies

### ISSUE THREAD

**Issue by andrewgregory** [dbsrgits/sql-translator#46]
In create_trigger PostgreSQL and DB2 use the trigger action as-is, which matches the documentation for `Trigger::action`, but SQLite and MySQL wrap the trigger action in `BEGIN ... END` causing an error if the action already includes `BEGIN ... END`.

**Comment by ribasushi** [comment]
Solved via https://github.com/dbsrgits/sql-translator/commit/e533bcddea
